email: info@danitso.com
title: Proxmox Provider
description: >-
  Terraform Provider for Proxmox.
baseurl: ""
url: ""
github_username: "danitso"

highlighter: rouge
markdown: kramdown
plugins:
  - github-pages
remote_theme: pmarsceill/just-the-docs

# Theme settings.
footer_content: 'Copyright &copy; 2019-2020 <a href="https://danitso.com/" target="_blank">Danitso</a> - Distributed under the <a href="https://github.com/danitso/terraform-provider-proxmox/blob/master/LICENSE" target="_blank">Mozilla Public License 2.0</a>'
heading_anchors: true
search_enabled: false
