name: Generate CHANGELOG

on:

  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for main branch
    steps:
      - uses: actions/checkout@v3

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG.md
          branch: main
          file_pattern: CHANGELOG.md
