name: Generate CHANGELOG

on:

  pull_request:
#    types: [ closed ]

  release:
    types: [ published ]

  issues:
    types: [ closed, edited ]

  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for main branch
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Import GPG key
        id: import_gpg_key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.BOT_GPG_PASSPHRASE }}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release_branch: main

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG.md
          branch: main
          file_pattern: CHANGELOG.md
          push_options: --force
          commit_author: ${{ steps.import_gpg_key.outputs.name }} <${{ steps.import_gpg_key.outputs.email }}>
          commit_user_email: ${{ steps.import_gpg_key.outputs.email }}
          commit_user_name: ${{ steps.import_gpg_key.outputs.name }}
