name: Generate CHANGELOG

on:
  pull_request:
#    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Commit files
#        env:
#          CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
#          CI_EMAIL: ${{ secrets.YOUR_GITHUB_EMAIL }}
#        run: |
#          git config --local user.email "$CI_EMAIL"
#          git config --local user.name "$CI_USER"
#          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

#      - name: Push changes
#        if: env.push == 'true'
#        env:
#          CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
#          CI_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN or GITHUB_TOKEN }}
#        run: |
#          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for PR
          file_pattern: CHANGELOG.md
