name: "Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Short Lived OAuth App Token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
          owner: "${{ github.repository_owner }}"
          repositories: "${{ github.event.repository.name }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Link Checker
        uses: lycheeverse/lychee-action@5c4ee84814c983aa7164eaee476f014e53ff3963 # v2.5.0
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          args: --base . --verbose --no-progress './**/*.md' './**/*.html' --exclude-path ./CONTRIBUTORS.md --exclude-path ./CHANGELOG.md

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
        if: steps.lychee.outputs.exit_code != 0
        with:
          state: open
          labels: |
            broken-links

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
        if: steps.lychee.outputs.exit_code != 0
        with:
          title: Broken links detected ðŸ”—
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ steps.app-token.outputs.token }}"
          labels: |
            broken-links
